In [68]:
# Importation des bibliothèques nécessaires
import pandas as pd
import unicodedata

# Fonction pour retirer les accents d'une chaîne de caractères
def retirer_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

df = pd.read_csv('allocine_V2_2.csv')

df['titre_original'] = df['titre_original'].apply(lambda x: retirer_accents(x) if isinstance(x, str) else x)
df['titre_original'] = df['titre_original'].replace({'ß': 'ss', '&': 'and', ' et ': ' and '})
df['titre_original'] = df['titre_original'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df['titre_original'] = df['titre_original'].replace('[^\w]', '', regex=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11869 entries, 0 to 11868
Data columns (total 53 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID_allocine              11869 non-null  int64
 1   realisateur              11723 non-null  object
 2   scenariste               10927 non-null  object
 3   duree                    11696 non-null  float64
 4   date                     11869 non-null  object
 5   day_of_month_sortie      11869 non-null  float64
 6   month_sortie             11869 non-null  float64
 7   day_of_week_sortie       11869 non-null  float64
 8   annee                    11869 non-null  float64
 9   titre_original           11869 non-null  object
 10  note_presse              11823 non-null  float64
 11  distributeur             11188 non-null  object
 12  budget                   3347 non-null   object
 13  premiere_semaine_france  10988 non-null  object
 14  acteur_1                 10170 non-null  object
 15  acteur_2                 9973 non-null   object
 16  acteur_3                 9838 non-null   object
 17  acteur_4                 9673 non-null   object
 18  Famille                  11745 non-null  object
 19  Comédie musicale         11745 non-null  object
 20  Drama                    11745 non-null  object
 21  Musical                  11745 non-null  object
 22  Comédie dramatique       11745 non-null  object
 23  Opéra                    11745 non-null  object
 24  Western                  11745 non-null  object
 25  Action                   11745 non-null  object
 26  Concert                  11745 non-null  object
 27  Aventure                 11745 non-null  object
 28  Historique               11745 non-null  object
 29  Biopic                   11745 non-null  object
 30  Guerre                   11745 non-null  object
 31  Erotique                 11745 non-null  object
 32  Drame                    11745 non-null  object
 33  Documentaire             11745 non-null  object
 34  Bollywood                11745 non-null  object
 35  Divers                   11745 non-null  object
 36  Fantastique              11745 non-null  object
 37  Spectacle                11745 non-null  object
 38  Péplum                   11745 non-null  object
 39  Espionnage               11745 non-null  object
 40  Animation                11745 non-null  object
 41  Romance                  11745 non-null  object
 42  Comédie                  11745 non-null  object
 43  Policier                 11745 non-null  object
 44  Arts Martiaux            11745 non-null  object
 45  Epouvante-horreur        11745 non-null  object
 46  Expérimental             11745 non-null  object
 47  Évènement Sportif        11745 non-null  object
 48  Thriller                 11745 non-null  object
 49  Science Fiction          11745 non-null  object
 50  Judiciaire               11745 non-null  object
 51  USA                      11869 non-null  bool
 52  France                   11869 non-null  bool
dtypes: bool(2), float64(6), int64(1), object(44)
memory usage: 4.6+ MB

In [69]:
# Import du CSV IMDB et sélection des colonnes
dftsv = pd.read_csv('data.tsv', sep='\t')
dftsv = dftsv[['tconst', 'originalTitle', 'runtimeMinutes']]

# Nettoyage de la colonne 'originalTitle' pour uniformiser le format du texte
dftsv['originalTitle'] = dftsv['originalTitle'].apply(lambda x: retirer_accents(x) if isinstance(x, str) else x)
dftsv['originalTitle'] = dftsv['originalTitle'].replace({'ß': 'ss', '&': 'and', ' et ': ' and '})
dftsv['originalTitle'] = dftsv['originalTitle'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
dftsv['originalTitle'] = dftsv['originalTitle'].replace('[^\w]', '', regex=True)

# Merge des DataFrame 'df' et 'dftsv' sur les titres originaux nettoyés
df = pd.merge(df, dftsv, left_on="titre_original", right_on="originalTitle", how="left")

# Conversion de la colonne 'runtimeMinutes' en numérique, avec gestion des erreurs pour obtenir des NaN en cas de problème
df['runtimeMinutes'] = pd.to_numeric(df['runtimeMinutes'], errors='coerce')

# Suppression des doublon de la colonne titre_original en prenant le plus proche en durée du film.
df['diff'] = (df['duree'] - df['runtimeMinutes']).abs()
df = df.sort_values(by=['titre_original', 'diff'])
df = df.drop_duplicates(subset='titre_original', keep='first')
df = df.drop(columns=['diff', 'originalTitle', 'runtimeMinutes'])
df = df.rename({"tconst": "ID_IMDB"}, axis=1)

df.info()

C:\Users\Nicolas\AppData\Local\Temp\ipykernel_7396\430419310.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  dftsv = pd.read_csv('data.tsv', sep='\t')

In [ ]:
# Import du CSV JPBOXoffice et sélection des colonnes
df_jpbox = pd.read_csv('jpbox_full.csv')
df_jpbox = df_jpbox[['ID', 'titre', 'duree_film']]

# Nettoyage de la colonne 'titre' pour uniformiser le format du texte
df_jpbox['titre'] = df_jpbox['titre'].apply(lambda x: retirer_accents(x) if isinstance(x, str) else x)
df_jpbox['titre'] = df_jpbox['titre'].replace({'ß': 'ss', '&': 'and', ' et ': ' and '})
df_jpbox['titre'] = df_jpbox['titre'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df_jpbox['titre'] = df_jpbox['titre'].replace('[^\w]', '', regex=True)

# Merge des DataFrame 'df' et 'df_jpbox' sur les titres originaux nettoyés
df = pd.merge(df, df_jpbox, left_on="titre_original", right_on="titre", how="left")

# Conversion de la colonne 'duree_film' en numérique, avec gestion des erreurs pour obtenir des NaN en cas de problème
df['duree_film'] = pd.to_numeric(df['duree_film'], errors='coerce')

df['diff'] = (df['duree'] - df['duree_film']).abs()
df = df.sort_values(by=['titre_original', 'diff'])
df = df.drop_duplicates(subset='titre_original', keep='first')
df = df.drop(columns=['diff', 'titre', 'duree_film'])
df = df.rename({"ID": "ID_JPbox"}, axis=1)


df.info()

In [ ]:
# Import du CSV TMDB et sélection des colonnes
df_tmdb = pd.read_csv('movies.csv')
df_tmdb = df_tmdb[['id', 'title', 'runtime']]

# Nettoyage de la colonne 'title' pour uniformiser le format du texte
df_tmdb['title'] = df_tmdb['title'].apply(lambda x: retirer_accents(x) if isinstance(x, str) else x)
df_tmdb['title'] = df_tmdb['title'].replace({'ß': 'ss', '&': 'and', ' et ': ' and '})
df_tmdb['title'] = df_tmdb['title'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df_tmdb['title'] = df_tmdb['title'].replace('[^\w]', '', regex=True)

# Merge des DataFrame 'df' et 'df_tmdb' sur les titres originaux nettoyés
df = pd.merge(df, df_tmdb, left_on="titre_original", right_on="title", how="left")

# Conversion de la colonne 'runtime' en numérique, avec gestion des erreurs pour obtenir des NaN en cas de problème
df['runtime'] = pd.to_numeric(df['runtime'], errors='coerce')

# Suppression des doublon de la colonne titre_original en prenant le plus proche en durée du film.
df['diff'] = (df['duree'] - df['runtime']).abs()
df = df.sort_values(by=['titre_original', 'diff'])
df = df.drop_duplicates(subset='titre_original', keep='first')
df = df.drop(columns=['diff', 'title', 'runtime'])
df = df.rename({"id": "ID_TMDB"}, axis=1)


df.info()

In [ ]:
df.to_csv('Allocine_v2_4.csv', index=False)