In [1]:
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import json
import re

# Démarrage du chronomètre pour calculer la durée d'exécution du script
start_time = time.time()

# Définition de la variable initial pour pour suivre la progression
pourcent = 71

# Définition de la plage d'ID dans l'url d'Allociné
depart_id = 10
total_id = 100

# Définition de la fonction pour scraper les données d'Allociné
def allocine_scrap(i):
    global pourcent
    # Initialisation des variables pour les informations à récupérer
    nom = recompenses = carriere_duree = films_series = naissance = pays = metier_1 = metier_2 = metier_3 = None
    
    try:
        # Construction de l'URL pour chaque film basé sur son ID
        url = f'https://www.allocine.fr/personne/fichepersonne_gen_cpersonne={i}.html'
        res = session.get(url, allow_redirects=True)

        # Print du % avec une intervalle de 24 tests
        pourcent += 1
        if pourcent == 72:
            print('Execution :', round(((i-depart_id)/(total_id-depart_id))*100, 2), '%')
            pourcent = 0
        
        # Vérification du statut de la réponse, retourne des "0" si le code HTTP n'est pas 200 ou si l'URL a été redirigée
        if res.status_code != 200:
            return i, "0", "0", "0", "0", "0", "0", "0", "0", "0"
        if res.url != url:
            return i, "0", "0", "0", "0", "0", "0", "0", "0", "0"
        
        # Utilisation de BeautifulSoup pour parser le contenu HTML
        soup = BeautifulSoup(res.content, 'lxml')

        # Extraction du nom de la personne.
        nom = soup.find('div', class_='titlebar-title titlebar-title-xl')

        # Extraction du premier bloc d'info (metiers, pays, date de naissance)
        infos = soup.find_all('div', class_="meta-body-item")
        for info in infos:
            info_next = info.find('span', class_='light')
            if info_next:
                if info_next.text.strip() == 'Métiers' or info_next.text.strip() == 'Métier':
                    metiers = info.find_all('span', class_=lambda x: x and 'dark-grey-link' in x)
                    if metiers:
                        if len(metiers) > 0 and metiers[0]:
                            metier_1 = metiers[0]
                        if len(metiers) > 1 and metiers[1]:
                            metier_2 = metiers[1]
                        if len(metiers) > 2 and metiers[2]:
                            metier_3 = metiers[2]
                    else:
                        metier_1 = info_next.find_next('strong')
                if info_next.text.strip() == 'Nationalité':
                    pays = info_next.find_next('div', class_='dark-grey')
                if info_next.text.strip() == 'Naissance':
                    naissance = info_next.find_next('span', class_=lambda x: x and 'dark-grey-link' in x)
        
        # Extraction du deuxième bloc d'info (durée de la carrière, nombre de films et series, nombre de recompenses)
        stats_numbers = soup.find_all(class_="stats-number")
        for stats_number in stats_numbers:
            stats_info = stats_number.find_next(class_="stats-info").get_text(strip=True)
            if "ans de carrière" in stats_info:
                carriere_duree = stats_number.get_text(strip=True)
            if "an de carrière" in stats_info:
                carriere_duree = stats_number.get_text(strip=True)
            elif "films et séries tournés" in stats_info:
                films_series = stats_number.get_text(strip=True)
            elif "film et série tourné" in stats_info:
                films_series = stats_number.get_text(strip=True)
            elif "prix" in stats_info:
                recompenses = stats_number.get_text(strip=True)
            elif "nominations" in stats_info:
                recompenses = 0
            elif "nomination" in stats_info:
                recompenses = 0
        
    # Gestion des exceptions liées aux requêtes HTTP
    except requests.exceptions.RequestException:
        return i, "0", "0", "0", "0", "0", "0", "0", "0", "0"
    
    # Retourne les données extraites ou des "0" si les données ne sont pas disponibles
    resultat = (
        i,
        nom.text.strip() if nom else "0",
        recompenses if recompenses else "0",
        carriere_duree if carriere_duree else "0",
        films_series if films_series else "0",
        naissance.text.strip() if naissance else "0",
        pays.text.strip() if pays else "0",
        metier_1.text.strip() if metier_1 else "0",
        metier_2.text.strip() if metier_2 else "0",
        metier_3.text.strip() if metier_3 else "0",
    )
    return resultat

# Initialisation d'un DataFrame pour stocker les données extraites   
df = pd.DataFrame(columns=['ID', 'nom', 'recompenses', 'carriere_duree', 'films_series', 'naissance', 'pays', 'metier_1', 'metier_2', 'metier_3']) 
session = requests.Session()

# Utilisation d'un ThreadPoolExecutor pour exécuter les scrapings en parallèle et utiliser les differents coeurs logique du PC.
with ThreadPoolExecutor(max_workers=12) as executor:

    # Soumission des tâches de scraping pour chaque ID de film entre 1 et la variable total_film
    tests = [executor.submit(allocine_scrap, i) for i in range(depart_id, total_id)]
    for test in tests:
        i, nom, recompenses, carriere_duree, films_series, naissance, pays, metier_1, metier_2, metier_3 = test.result()
        variables = (nom, recompenses, carriere_duree, films_series, naissance, pays, metier_1, metier_2, metier_3)
        if any(v != "0" for v in variables):
            df.loc[i] = [i, nom, recompenses, carriere_duree, films_series, naissance, pays, metier_1, metier_2, metier_3]
            #display(df.loc[i])

# Arrêt du chronomètre et affichage de la durée d'exécution
end_time = time.time()
execution_time = end_time - start_time
print(f"Le script a pris {execution_time} secondes pour s'exécuter.")

# Sauvegarde des résultats dans un fichier CSV
df.to_csv(f'allocine_{depart_id}_{total_id}.csv', index=False)

# Affichage du DataFrame final
display(df)

Execution : 5.56 %
Execution : 84.44 %
Le script a pris 16.47884464263916 secondes pour s'exécuter.

,ID,nom,recompenses,carriere_duree,films_series,naissance,pays,metier_1,metier_2,metier_3
10,10,Harvey Keitel,1,57,160,13 mai 1939,Américain,Acteur,Producteur exécutif,Coproducteur
11,11,Dianne Wiest,4,43,59,28 mars 1948,Américaine,Actrice,0,0
12,12,Jane Kaczmarek,0,41,51,21 décembre 1955,Américaine,Actrice,0,0
13,13,George Martin,0,44,34,15 août 1929,Indéfini,Acteur,Scénariste,0
14,14,Christian-Jaque,4,57,61,4 août 1904,Français,Réalisateur,Scénariste,Chef décorateur
...,...,...,...,...,...,...,...,...,...,...
95,95,Roger Moore,0,72,65,14 octobre 1927,Britannique,Acteur,Réalisateur,Coproducteur
96,96,Maud Adams,0,42,27,12 février 1945,Suédoise,Actrice,0,0
97,97,Kristina Wayborn,0,23,10,24 septembre 1950,Suédoise,Actrice,0,0
98,98,Kabir Bedi,0,40,28,16 janvier 1946,Indien,Acteur,0,0
99,99,Vijay Amritraj,0,4,2,0,Indéfini,Acteur,0,0